### ISSUE TITLE
F3-WG-Issue-7: Compatibility of BGP-CT and BGP-CAR to SR-PCE (Shraddha Hegde) 

### ISSUE THREAD

**Issue by sa1231-coder** [ietf-wg-idr/draft-ietf-idr-bgp-car#12]
•	CT: Consider how CT implements or interoperates with all the constructs in RFC 9256.  Provide a short section in your document regarding support.  
•	CT: Describe the limits of any community, extended community, wide-community regarding color when interacting with CT’s mapping community. 
•	CAR: Consider how CAR implements or interoperates with all the constructs in RFC9256. CAR: Provide a short section in your document regarding support. 
•	CAR: Describe the limits of any community, extended community or wide-community regarding color.  Describe how any of these limits interact with LCM.

**Comment by sa1231-coder** [comment]
CAR is inherently compatible with SR-PCE. It uses the identical ‘Color’ construct for both service steering (Color-ExtComm), and for routing (CAR routes & LCM). Section 1.2 illustrates the seamless compatibility. CAR does not require separate mapping communities or number spaces that need to be mapped to the color.
 
CAR also does not preclude any typical BGP attributes based route-policies from being used to augment routing. There are no specific constraints w.r.t CAR.

**Comment by suehares** [comment]
This issue had two points:
**1.  Consider how CAR implements or interoperates with _all the constructs in RFC9256._**
Please provide a short section on support.  Your section 1.2 provides a good illustration, but it does not cover if "all the constructs of RFC9256" are supported. 

If you believe you support "all the constructs in RFC9256", please ask Bruno or Joel for a review of your document (-01.txt) to see it supports "all constructs".  If you wish to constrain the CAR support to a subset of the RFC9256 constructs, please add a paragraph. 

**2.  CAR: Describe the limits of any community, extended community or wide-community regarding color. Describe how any of these limits interact with LCM.**

I do not see where you provide me with an answer the second sub-issue above.

**Comment by suehares** [comment]
Section 3 contains the definition support for RFC9256.

**Comment by suehares** [comment]
You do not support RFC 9012 Color SubTLV.
You do support Color in NLRI and Extended Communities (RFC9012). 

Wide color community - Sue will research where it is mentioned.    We will consider this closed if there are no wide  community with color From Robert Raszuk.

**Comment by suehares** [comment]
No wide community color pointed to by Robert or other respondents.
