### ISSUE TITLE
Create a status text with specific sections for resolution of the document. 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-car#15]
It would be helpful to have a specific file that lists where you updated to resolve each issues.  
I will re-open issues F3-CAR-Issues-01 so you can update a file from the issue. 

See the example from:  
https://github.com/ietf-wg-idr/draft-ietf-idr-bgp-ct/blob/main/github-issues-status.txt

**Comment by sa1231-coder** [comment]
Added https://github.com/ietf-wg-idr/draft-ietf-idr-bgp-car/blob/working_tree/github_issues_update.txt

**Comment by sa1231-coder** [comment]
done
