### ISSUE TITLE
WG-LC-RTG-DIR-1 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-car#16]
**Reviewer: Ben Niven-Jenkins**
****Review result: Has Issues**
Mail archive link:** 
https://mailarchive.ietf.org/arch/msg/idr/0X_q_e09ejtb0NZQ25smUrklwmQ/

Hello

I have been selected to do a routing directorate “early” review of this draft.
https://datatracker.ietf.org/doc/draft-ietf-mpls-rfc3107bis/

The routing directorate will, on request from the working group chair, perform
an “early” review of a draft before it is submitted for publication to the
IESG. The early review can be performed at any time during the draft’s lifetime
as a working group document. The purpose of the early review depends on the
stage that the document has reached.

For more information about the Routing Directorate, please see
https://wiki.ietf.org/en/group/rtg/RtgDir

Document: draft-ietf-idr-bgp-car-02
Reviewer: Ben Niven-Jenkins
Review Date: 31 July 2023
Intended Status: Experimental

Summary:
I have some minor concerns about this document that I think should be resolved
before it is submitted to the IESG.

Comments:
The document provides lots of details in the main sections and examples in the
appendices. I think that is generally ready to be published. The only
suggestion I would have is to provide a short overview introducing BGP CAR and
color aware routing before leaping into terminology and the details of the BGP
CAR SAFI. Expanding the introduction section with an extra paragraph or two
would be sufficient.

Thanks
Ben

**Comment by suehares** [comment]
DJ's response: 
**Mail archive link: 
https://mailarchive.ietf.org/arch/msg/idr/0DL4N39sIPOqlCJUMo7UITkdCUI/**

We appreciate your review of the CAR draft. We will add some overview text as you suggest.

WG Chair's comment: 
Text in introduction section should be proposed here:

**Comment by dhrao1** [comment]
Follow-up review and response from Ben indicating the latest draft changes addressed his comments.

https://mailarchive.ietf.org/arch/msg/idr/2pvoE8MclWZKUT9N4eZmzOJF59k/
