### ISSUE TITLE
RTG-DIR review of -05 (Mike McBride) 

### ISSUE THREAD

**Issue by suehares** [ietf-wg-idr/draft-ietf-idr-bgp-car#28]
### RTG-DIR-01 
1. Introduction:

OLD:
BGP CAR distributes distinct routes to a destination network endpoint such as a
PE router, for different intents or colors.

NEW:
BGP CAR distributes distinct routes to a destination network endpoint, such as
a PE router, for different intents or colors.

### RTG-DIR-02 
OLD:
BGP CAR adheres to the flat routing model of BGP-IP/LU...

NEW:
BGP CAR adheres to the flat routing model of BGP-IP/LU(Labeled Unicast)...
*Unless you think LU is as understood as IP and having no need for definition.

### RTG-DIR-03 
1.1 Terminology (Resolution vs Steering):

OLD:
In this document and consistently with the terminology of
the SR Policy document [[RFC9256](https://datatracker.ietf.org/doc/rfc9256/)], steering is used to
describe the mapping of a service route onto a BGP CAR
path while the term resolution is preserved for the
mapping of an inter-domain BGP CAR route on an intra-
domain color-aware path.

NEW:
In this document, and consistently with the terminology of
the SR Policy document [[RFC9256](https://datatracker.ietf.org/doc/rfc9256/)], steering is used to
describe the mapping of a service route onto a BGP CAR
path. The term resolution is preserved for the
mapping of an inter-domain BGP CAR route on an intra-
domain color-aware path.

### RTG-DIR-04 

1.2 Illustration

OLD:
*Control-Plane: a node should not install a (E, C) path if it does not need it.

NEW:
*Control-Plane: a node should not install a (E, C) path if it's not
participating in that color-aware path.

### RTG-DIR-05 

2.11.  Error Handling

OLD:
When the error determined allows for the router to skip the
malformed NLRI(s) and continue processing of the rest of the update
message, then it MUST handle such malformed NLRIs as 'Treat-as-
withdraw'.

NEW:
When the error determined allows for the router to skip the
malformed NLRI(s), and continue processing of the rest of the update
message, then it MUST handle such malformed NLRIs as 'Treat-as-
withdraw'.

### RTG-DIR-06 

7.1.1.  Routed Service SID

OLD:
The intent-aware transport path to the locator of the egress PE is
provided by underlay IP routing, for instance, IGP Flex-Algo
[[RFC9350](https://datatracker.ietf.org/doc/rfc9350/)] within a domain, and BGP-CAR across multiple IGP domains
or BGP ASNs.

NEW:
The intent-aware transport path to the locator of the egress PE is
provided by underlay IP routing such as IGP Flex-Algo
[[RFC9350](https://datatracker.ietf.org/doc/rfc9350/)] (within a domain) and BGP-CAR (across multiple IGP domains
or BGP ASNs).

*this makes more sense to me anyway.

**Comment by dhrao1** [comment]
We had updated the text for Mike's comments.

**Comment by suehares** [comment]
The issues raised in RTG-DIR-01, RTG-DIR-02, RTG-DIR-03, RTG-DIR-04, RTG-DIR-05, and RTG-DIR-06  were resolved with the publication of draft-ietf-idr-car-06. 

[You can see the differences in a comparison of -05 and -06]
