### ISSUE TITLE
F3-CAR-Issue-4: CAR Routing in Non-Agreeing Color domains for Anycast EPs

### ISSUE THREAD

**Issue by sa1231-coder** [ietf-wg-idr/draft-ietf-idr-bgp-car#4]
-Clarify paragraph 2 in Section 10 to include assumptions regarding coordination of shared ANYCAST service used across multiple color domains (This issues links to F3-CAR-Issue-4).
-Link revised paragraph 2 in section 10 to Appendix A.7
-Revise Appendix A.7 (or create a new) to specifically detail how an ANYCAST Address will operate in non-agree color domains.

**Comment by sa1231-coder** [comment]
Section 10 (Manageability Considerations) is updated to explicitly state that color coordination is not required unless shared IP address is needed.

Section A.7 updated for shared IP address across different color domains.

**Comment by suehares** [comment]
Shepherd comment: 

The changes (edits and additions) to section 10 and A.7 need to be validated together with this focus.  Use the call text of: 

**F3-CAR-Is F3-CAR-Issue-4: CAR Routing in Non-Agreeing Color domains for Anycast EPs**

I suggest the sequencing of calls should be: 

1. F3-CAR-Issue 2 - with sub-calls a-f done in order 
2. F3-CAR-Issue 3 
3. F3-CAR-Issue-1 and F3-CAR-Issue 4  (you may do these concurrently or sequentially)
4. F3-CAR-Issue-5

I am fine with the draft-ietf-idr-bgp-car-01.txt being published as long as you realize the only text that stays is the text agreed upon by the IDR WG.

**Comment by suehares** [comment]
this issue is considered closed with draft-ietf-idr-bgp-car-01.txt.
