### ISSUE TITLE
F3-WG-Issue-2: Support for SR-v6

### ISSUE THREAD

**Issue by sa1231-coder** [ietf-wg-idr/draft-ietf-idr-bgp-car#7]
Working on the updates.

**Comment by suehares** [comment]
Just to keep track this is what should be included:

1. WG  (chair + Jingrong) should agree upon a topology example 
2. CAR: Provide an illustration of SRv6 data plane (e.g., E2E SRv6 & intra-domain SRv6) based on a sample topology
2. CAR: (DJ) Add additional options and operational considerations that do need to be described. (CAR authors planned in July to include them along with illustrations in the next version of the draft.) 
 
On item 1, have you assumed a topology example?  

If so, we should check this example on the list. 

Cheerily, Sue

**Comment by suehares** [comment]
[consider draft-wang-idr-cpr](https://datatracker.ietf.org/doc/html/draft-wang-idr-cpr-01) for its operational/deployment needs. 

Please discuss these operational needs with the authors of the draft.

**Comment by suehares** [comment]
I'm going to check with Jie Dong on Monday (US Time).

**Comment by sa1231-coder** [comment]
Jingrong is fine with the latest text. Please see the thread below
 
 
From: Jingrong Xie <[xiejingrong=40huawei.com@dmarc.ietf.org](mailto:xiejingrong=40huawei.com@dmarc.ietf.org)>
Date: Thursday, November 30, 2023 at 11:47 PM
To: Swadesh Agrawal (swaagraw) <[swaagraw@cisco.com](mailto:swaagraw@cisco.com)>
Cc: Dhananjaya Rao (dhrao) <[dhrao@cisco.com](mailto:dhrao@cisco.com)>
Subject: RE: [Idr] WG LC for draft-ietf-idr-bgp-car-02 (7/10/2023 to 7/24/2023) - Follow-up on Adoption call issue regarding SRv6 support

Hi Swadesh,
 
Thanks for your reply on my comments.
Those comments are all minor ones and suggestions, and I am fine with your point to keep them in current shape.
 
One small nit in the last part of appendix C.2 (just before C.3):
 
==========Current text begin===========
   Packet forwarding
 
   @E1:   IPv4 VRF V/v => H.Encaps.red <B:C13:121:END::, B:C11:2:DT4::>
   @121: My SID table: B:C13:121:END:: => Update DA with B:C11:2:DT4::
   @121: IPv6 Table: B:C11::/32 => H.Encaps.red <B:C12:231:END::>
   @231: My SID table: B:C12:231:END:: => Update DA with B:C11:2:DT4::
   @231: IPv6 Table B:C11:2::/48 => forward via ISISv6 FA path to E2
   @E2: My SID table B:C11:2:DT4:: =>pop the outer header and lookup the
                                      inner DA in the VRF
==========Current text end===========
 
==========Correct text Begin (the line with first "@231")===========
   Packet forwarding
 
   @E1:   IPv4 VRF V/v => H.Encaps.red <B:C13:121:END::, B:C11:2:DT4::>
   @121: My SID table: B:C13:121:END:: => Update DA with B:C11:2:DT4::
   @121: IPv6 Table: B:C11::/32 => H.Encaps.red <B:C12:231:END::>
   @231: My SID table: B:C12:231:END:: => pop the outer header encapsulated.
SA>> Ack. Will update the text to “Remove the outer IPv6 Header”
   @231: IPv6 Table B:C11:2::/48 => forward via ISISv6 FA path to E2
   @E2: My SID table B:C11:2:DT4:: =>pop the outer header and lookup the
                                      inner DA in the VRF
==========Correct text End===========
 
One more discussion/remind about removing the SRH with SL==0 by node-121:
   If B:C13:121:END:: is an End SID with PSP flavor, then it is right according to RFC8986 to remove the SRH with SL==0 (after update DA).
   if B:C13:121:END:: is an End SID without PSP flavor, then it is right to NOT remove the SRH with SL==0 (after update DA) as illustrated in C.2 currently.
   Therefore, I am fine to keep it unchanged, but just want to discuss/remind on this point.
SA>> Sure. It’s an example with PSP flavor, an optimized implementation should support it.
 
Regards,
Jingrong
 
本邮件及其附件可能含有华为公司的保密信息，仅限于发送给上面地址中列出的个人或群组。禁止任何其他人以任何形式使用（包括但不限于全部或部分地泄露、复制、或散发）本邮件中的信息。如果您错收了本邮件，请您立即电话或邮件通知发件人并删除本邮件！
This e-mail and its attachments may contain confidential information from HUAWEI, which is intended only for the person or entity whose address is listed above. Any use of the information contained herein in any way (including, but not limited to, total or partial disclosure, reproduction, or dissemination) by persons other than the intended recipient(s) is prohibited. If you receive this e-mail in error, please notify the sender by phone or email immediately and delete it!
