### ISSUE TITLE
F3-WG-Issue-4

### ISSUE THREAD

**Issue by sa1231-coder** [ietf-wg-idr/draft-ietf-idr-bgp-car#9]
•	Chair + Ketan: Define an example of a service layer intent versus transport intent. 
•	CT: Add a section to discuss how color is implement in the VPN service layer. 
•	CT: Add a definition of intent that aligns with Spring and other IETF/IRTF WGs
•	CAR: Add a section to discuss how color is implemented in the VPN service layer
•	CAR: Clarify the definition of intent to align with Spring and other IETF/IRTF WGs

**Comment by sa1231-coder** [comment]
Section 3 already discusses the automated steering of services over CAR transport is as per I-D.ietf-spring-segment-routing-policy. 
Also, Section 8 describes the implementation for VPN CAR.

**Comment by suehares** [comment]
Swadesh and DJ: 

Again, the first step is for you Ketan to propose an example of the service layer intent versus transport layer intent.  

After he defines the example, he can start a IDR WG discussion with the subject: 
**F3-WG-Issue-4a: Example of Intent at Service level [Ketan Talaulikar]** 

Ketan can sponsor and handle the discussion.  I will judge consensus. 

Again, I hope after we get the example, your comments are accurate.  We cannot tell until we get the example. 

This issue stays open until you complete calls the four steps below 

1. **F3-WG-Issue-4a: Example of Intent at Service level [Ketan Talaulikar]** 
2.  F3-WG-Issue-4b: CAR inclusion of example 
You should include the Intent at Service level example, and provide the text. 
Do a call to make sure the example is correct. 

3.  F3-WG-Issue-4c: Implementation of color at VPN Service level. 
After you do the first two calls, you can the IDR WG if your section 3 and section 8 are sufficient. 

4. F3-WG-Issue-4d: Alignment with Spring and other WGs. 

After you finish any changes from the F3-WG-Issue-4a, F3-WG-Issue-4b, and F3-WG-Issue-4c, you could ask the Spring Chairs regarding alignment. 

This issue needs to stay open until you clear all the sub-issues.  You can open other issues for the specifics of the call.

**Comment by suehares** [comment]
This issue stays open until calls for  F3-Wg-Issues-4a, F3-WG-Issue-4B, F3-WG-Issue-4c, F3-Issue-4d are complete.

**Comment by suehares** [comment]
Close with Intent definitions by F3-CAR-Issue-1. Ketan will personally review.

**Comment by suehares** [comment]
This item will be closed after an final review by Ketan to assume that his comments have been met.

**Comment by dhrao1** [comment]
No additional comments.
